[tool.pytest.ini_options]
addopts = [
    "--driver", "Edge",
    "--screenshot", "only-on-failure",
    "-n", "auto",
    "--alluredir=allure",
    "--driver-path=D:\\img\\driver\\msedgedriver.exe"
]

