[tool.pytest.ini_options]
addopts = [
    "--driver", "Edge",
    "--screenshot", "only-on-failure",
    "--video", "retain-on-failure",
    "-n", "auto",
    "--alluredir=allure",
    # "--driver-path=D:\\Programs\\driver\\edgedriver_win64\\msedgedriver.exe"
]
markers = [
    "slow: marks tests as slow"
]
